version: "{build}"

branches:
  only:
    - master

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - mkdir c:\gopath
  - go get github.com/mikioh/ipoam

build_script:
  - go test -v -race
